import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Hello world</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Link href='/about-me'>About Me</Link>
        <button
          onClick={() => {
            router.push("/contact");
          }}
        >
          연락하기
        </button>
      </main>
    </div>
  );
}
